server:
  port: 8762

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: eureka-service
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
