server:
  port: 8762

spring:
  application:
    name: consort-eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
    prefer-ip-address: true
    non-secure-port: 8762

management:
  endpoints:
    web:
      exposure:
        include: health,info